# Generated by Django 5.2.6 on 2025-09-11 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
